Greeting.create(message: "Hello! How are you today?")
Greeting.create(message: "Hi there! I hope you're having a great day.")
Greeting.create(message: "Good morning! I hope you slept well.")
Greeting.create(message: "Hey, how's it going? What's new?")
Greeting.create(message: "Greetings and salutations! I trust you're doing well.")
